export enum WorkflowState {
  Draft = "draft",
  Grilling = "grilling",
  SpecReady = "spec_ready",
  Planning = "planning",
  PlanReview = "plan_review",
  AwaitingPlanApproval = "awaiting_plan_approval",
  Implementing = "implementing",
  CodeReview = "code_review",
  ScopeReview = "scope_review",
  StaticVerification = "static_verification",
  TestVerification = "test_verification",
  RuntimeVerification = "runtime_verification",
  Fixing = "fixing",
  SecurityReview = "security_review",
  FinalGate = "final_gate",
  FinalSummary = "final_summary",
  AwaitingPushApproval = "awaiting_push_approval",
  Committing = "committing",
  Pushing = "pushing",
  Complete = "complete",
  Failed = "failed",
}
