/**
 * Recorded architecture decision for installing Agent Workflow Kit into a repository.
 *
 * This milestone documents the decision and the data a future installer will need. It deliberately
 * implements no installer, no scaffolding command, and no framework copy: installing is milestone
 * work that is not started here.
 */

export interface InstallPolicyEntry {
  readonly path: string;
  readonly reason: string;
}

export const INSTALL_POLICY_DECISION =
  "Installing Agent Workflow Kit into a repository must not vendor the framework. The framework implementation stays in the installed package; the repository receives thin configuration, and only the configuration is version controlled.";

/** Files a user is meant to read, edit, and commit. */
export const VERSION_CONTROLLED_ENTRIES: readonly InstallPolicyEntry[] = [
  {
    path: "AGENTS.md",
    reason: "Repository guidance the agents read, and the place project conventions live.",
  },
  {
    path: ".agentflow/config.*",
    reason: "Workflow configuration for this repository, not runtime state.",
  },
  {
    path: "customized policies and workflow overrides",
    reason: "Deliberate local policy changes must be reviewable in a diff.",
  },
  {
    path: "skills.lock",
    reason:
      "Pinned external skill resolution, once external skills exist. Absent until then; an empty lock file is never created.",
  },
  {
    path: ".opencode/agents/*.md and opencode.json",
    reason: "The minimal agent-adapter configuration the OpenCode adapter requires.",
  },
];

/** Files produced by running the workflow. They are ignored by default, not committed. */
export const RUNTIME_GENERATED_ENTRIES: readonly InstallPolicyEntry[] = [
  {
    path: ".agentflow/features/",
    reason:
      "Feature sessions, workflow event logs, controlled artifacts including verification evidence and fix history, and anything else a run produces.",
  },
  {
    path: ".agentflow/cache/",
    reason: "Derived caches. Safe to delete; never a source of truth.",
  },
  {
    path: ".agentflow/recordings/",
    reason: "Runtime recordings of agent sessions.",
  },
  {
    path: ".agentflow/tmp/",
    reason: "Temporary files from an in-flight run.",
  },
  {
    path: ".agentflow/locks/",
    reason: "Per-feature lock directories, which are only meaningful while a process holds them.",
  },
  {
    path: ".agentflow/*.lock",
    reason: "Advisory lock files.",
  },
];

export const DEFAULT_GITIGNORE_LINES: readonly string[] = [
  "# Agent Workflow Kit runtime state. Generated by a run, not authored by a human.",
  ...RUNTIME_GENERATED_ENTRIES.map((entry) => entry.path),
];

/**
 * Future artifact-tracking modes. Not implemented: a mode may only be chosen once an installer
 * exists, and choosing one must never change what the orchestrator verifies.
 */
export const ARTIFACT_TRACKING_MODES = ["local", "summary", "all"] as const;

export type ArtifactTrackingMode = (typeof ARTIFACT_TRACKING_MODES)[number];

export const DEFAULT_ARTIFACT_TRACKING_MODE: ArtifactTrackingMode = "local";

/** The framework implementation is a package dependency, never a directory copied into a project. */
export const VENDORED_FRAMEWORK_PATHS: readonly string[] = [
  "core/",
  "orchestration/",
  "adapters/",
  "apps/",
  "templates/",
  "fixtures/",
  "tests/",
];
